In [1]:
import time
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
from functools import reduce
import time

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Clean the lineup dataset, Generate cluster profiles

Steps
- Worksheet at front
- Clean lineup dataset by removing lineups where all players aren't in the player cluster dataset
  - save clean datasets
- Get line lineup cluster profiles
  - save lineup cluster dataset


In [5]:
df_4line = pd.read_csv('datasets/lineups/4man_lineups_300min_1997_2020.csv', index_col=0)
df_players = pd.read_csv('datasets/master_player_stats_bio_bpm_clusters.csv', index_col=0)

In [9]:
df_4line = df_4line[df_4line['year'] >= 2000]
df_4line.shape

(5253, 27)

### Build lineup profile
- for each lineup need to get the player id's
- for need to sum the player bpm_cluster profiles
- add the lineup clusters - bpm and non-bpm clusters


In [112]:
r1 = df_4line.iloc[0]
r1id = r1['player_ids'].split(', ')
r1id
year = r1['year']


lineup_bpm_clusters = np.zeros(12)
lineup_nonbpm_clusters = np.zeros(12)

#     cluster_bpm_cols = df_players.columns[df_players.columns.str.contains('cluster_[0-9]|1[0-1]_bpm', regex=True)].values
#     cluster_nonbpm_cols = df_players.columns[df_players.columns.str.contains('cluster_[0-9]|1[0-1]', regex=True)].values

cluster_bpm_cols = [f'cluster_{n}_bpm' for n in range(12)]
cluster_nonbpm_cols = [f'cluster_{n}' for n in range(12)]


# lineup_bpm_clusters = pd.DataFrame({col: [0.0] for col in cluster_bpm_cols}, index=[r1.name])


# print(lineup_bpm_clusters)

df_lineup_clusters = pd.DataFrame({col: 0.0 for col in cluster_bpm_cols+cluster_nonbpm_cols}, index=[r1.name])
# print(df_lineup_clusters)

for pid in r1id:
    print(pid)
    player = df_players[(df_players['year'] == year) & (df_players['player_id'] == pid)]
    
    print(player[cluster_bpm_cols])
    print(player[cluster_nonbpm_cols])
    
    df_lineup_clusters[cluster_bpm_cols] += player[cluster_bpm_cols].to_numpy().reshape(-1)
    df_lineup_clusters[cluster_nonbpm_cols] += player[cluster_nonbpm_cols].to_numpy().reshape(-1)
    
    print('\n\n')
    
print(df_lineup_clusters[cluster_nonbpm_cols])
    
# #     print(player[cluster_bpm_cols].to_numpy().round(2))
# #     print(lineup_bpm_clusters.round(2))
# #     print('\n\n')
# print(lineup_bpm_clusters.round(2))
# print(lineup_nonbpm_clusters.round(2))
# print('\n\n')

# lineup = pd.DataFrame(r1)
# print(lineup)
# lineup[cluster_bpm_cols] = lineup_bpm_clusters
# print(lineup)
    
    
# #     player_cluster_bpm = player.loc[:, df_players.columns[df_players.columns.str.contains('cluster_([0-9]|1[0-1])_bpm', regex=True)]]
# #     print(player_cluster_bpm.to_numpy())
    
#     #     print(player_cluster)

# # a = df_4line['player_ids'][0:1].str.split(', ')



['colesbi01', 'hendeal01', 'jacksji01', 'mutomdi01']

colesbi01
                  cluster_0_bpm  cluster_1_bpm  cluster_2_bpm  cluster_3_bpm  \
player                                                                         
Bimbo Coles 2000           -0.0           -0.0           -0.0           -0.0   

                  cluster_4_bpm  cluster_5_bpm  cluster_6_bpm  cluster_7_bpm  \
player                                                                         
Bimbo Coles 2000           -0.0      -0.000788           -0.0           -0.0   

                  cluster_8_bpm  cluster_9_bpm  cluster_10_bpm  cluster_11_bpm  
player                                                                          
Bimbo Coles 2000           -0.0           -0.0        -2.19921            -0.0  
                  cluster_0  cluster_1  cluster_2  cluster_3  cluster_4  \
player                                                                    
Bimbo Coles 2000        0.0        0.0        0.0        0.0        0.0   

                  cluster_5  cluster_6 

In [224]:

def get_lineup_cluster_profile(lineup, df_players):
    """
    Function for building lineup cluster profiles (bpm weighted and non bpm weighted)
    based on player ids and year using a dataset with player cluster assignments and bpm weights.
    
    Return a 1 row dataframe with same index as lineup and columns for cluster profiles.
    """
    
#     print('Called with lineup:', lineup)
    
    player_ids = lineup['player_ids'].split(', ')
    cluster_bpm_cols = [f'cluster_{n}_bpm' for n in range(12)]
    cluster_nonbpm_cols = [f'cluster_{n}' for n in range(12)]    
    df_lineup_clusters = pd.DataFrame({col: 0.0 for col in cluster_bpm_cols+cluster_nonbpm_cols}, index=[lineup.name])
    print('all lineup pids:', player_ids)
    print('year:', year)
    for pid in player_ids:
        player = df_players[(df_players['year'] == year) & (df_players['player_id'] == pid)]
        print('player: ', pid)
        df_lineup_clusters[cluster_bpm_cols] += player[cluster_bpm_cols].to_numpy().reshape(-1)
        df_lineup_clusters[cluster_nonbpm_cols] += player[cluster_nonbpm_cols].to_numpy().reshape(-1)
    
#     print('returning:', df_lineup_clusters)
    print(df_lineup_clusters.shape)
    print('---------------------')
    return df_lineup_clusters

In [ ]:
['abdursh01', 'johnsde03', 'mohamna01', 'terryja01']

In [191]:
df_players[df_players['player_id'] == 'mohamna01']

player_id pos  age team_id   g    mp   per  ts_pct  \
player                                                                   
Nazr Mohammed 2001  mohamna01   C   23     TOT  58   912  19.2   0.520   
Nazr Mohammed 2002  mohamna01   C   24     ATL  82  2168  14.0   0.490   
Nazr Mohammed 2004  mohamna01   C   26     TOT  80  1611  16.1   0.542   
Nazr Mohammed 2005  mohamna01   C   27     TOT  77  1933  16.4   0.521   
Nazr Mohammed 2006  mohamna01   C   28     SAS  80  1389  15.0   0.560   
Nazr Mohammed 2007  mohamna01   C   29     DET  51   773  16.5   0.554   
Nazr Mohammed 2008  mohamna01   C   30     TOT  82  1650  15.8   0.533   
Nazr Mohammed 2010  mohamna01   C   32     CHA  58   984  19.6   0.578   
Nazr Mohammed 2011  mohamna01   C   33     TOT  75  1280  15.9   0.538   
Nazr Mohammed 2012  mohamna01   C   34     OKC  63   692  11.0   0.477   
Nazr Mohammed 2013  mohamna01   C   35     CHI  63   693  10.8   0.414   

                    fg3a_per_fga_pct  fta_per_fga_pct  ...  cluster_2_bpm  \
player                                                 ...                  
Nazr Mohammed 2001             0.003            0.341  ...           -0.0   
Nazr Mohammed 2002             0.001            0.311  ...           -0.0   
Nazr Mohammed 2004             0.000            0.358  ...           -0.0   
Nazr Mohammed 2005             0.002            0.377  ...           -0.0   
Nazr Mohammed 2006             0.000            0.382  ...           -0.0   
Nazr Mohammed 2007             0.000            0.369  ...           -0.0   
Nazr Mohammed 2008             0.002            0.309  ...           -0.0   
Nazr Mohammed 2010             0.000            0.365  ...            0.0   
Nazr Mohammed 2011             0.002            0.250  ...           -0.0   
Nazr Mohammed 2012             0.006            0.136  ...           -0.0   
Nazr Mohammed 2013             0.011            0.261  ...           -0.0   

                    cluster_3_bpm  cluster_4_bpm  cluster_5_bpm  \
player                                                            
Nazr Mohammed 2001           -0.0           -0.0           -0.0   
Nazr Mohammed 2002           -0.0           -0.0           -0.0   
Nazr Mohammed 2004           -0.0           -0.0           -0.0   
Nazr Mohammed 2005           -0.0           -0.0           -0.0   
Nazr Mohammed 2006           -0.0           -0.0           -0.0   
Nazr Mohammed 2007           -0.0           -0.0           -0.0   
Nazr Mohammed 2008           -0.0           -0.0           -0.0   
Nazr Mohammed 2010            0.0            0.0            0.0   
Nazr Mohammed 2011           -0.0           -0.0           -0.0   
Nazr Mohammed 2012           -0.0           -0.0           -0.0   
Nazr Mohammed 2013           -0.0           -0.0           -0.0   

                    cluster_6_bpm  cluster_7_bpm  cluster_8_bpm  \
player                                                            
Nazr Mohammed 2001           -0.0      -1.499979           -0.0   
Nazr Mohammed 2002           -0.0      -3.800000           -0.0   
Nazr Mohammed 2004           -0.0      -1.400000           -0.0   
Nazr Mohammed 2005           -0.0      -1.800000           -0.0   
Nazr Mohammed 2006           -0.0      -1.999998           -0.0   
Nazr Mohammed 2007           -0.0      -1.900000           -0.0   
Nazr Mohammed 2008           -0.0      -2.299995           -0.0   
Nazr Mohammed 2010            0.0       0.500000            0.0   
Nazr Mohammed 2011           -0.0      -0.000000           -0.0   
Nazr Mohammed 2012           -0.0      -2.400000           -0.0   
Nazr Mohammed 2013           -0.0      -3.599986           -0.0   

                    cluster_9_bpm  cluster_10_bpm  cluster_11_bpm  
player                                                             
Nazr Mohammed 2001           -0.0            -0.0            -0.0  
Nazr Mohammed 2002           -0.0            -0.0            -0.0  
Nazr Mohammed 2004           -0.0      

## There are players in lineup data who aren't in player  df

In [225]:
cluster_bpm_cols = [f'cluster_{n}_bpm' for n in range(12)]
cluster_nonbpm_cols = [f'cluster_{n}' for n in range(12)]
df_4line[cluster_bpm_cols+cluster_nonbpm_cols] = df_4line.apply(lambda lineup: get_lineup_cluster_profile(lineup, df_players), axis=1)
df_4line

all lineup pids: ['colesbi01', 'hendeal01', 'jacksji01', 'mutomdi01']
year: 2000
player:  colesbi01
player:  hendeal01
player:  jacksji01
player:  mutomdi01
(1, 24)
---------------------
all lineup pids: ['hendeal01', 'jacksji01', 'mutomdi01', 'rideris01']
year: 2000
player:  hendeal01
player:  jacksji01
player:  mutomdi01
player:  rideris01
(1, 24)
---------------------
all lineup pids: ['colesbi01', 'hendeal01', 'mutomdi01', 'rideris01']
year: 2000
player:  colesbi01
player:  hendeal01
player:  mutomdi01
player:  rideris01
(1, 24)
---------------------
all lineup pids: ['colesbi01', 'jacksji01', 'mutomdi01', 'rideris01']
year: 2000
player:  colesbi01
player:  jacksji01
player:  mutomdi01
player:  rideris01
(1, 24)
---------------------
all lineup pids: ['colesbi01', 'hendeal01', 'jacksji01', 'rideris01']
year: 2000
player:  colesbi01
player:  hendeal01
player:  jacksji01
player:  rideris01
(1, 24)
---------------------
all lineup pids: ['hendeal01', 'jacksji01', 'mutomdi01', 'terryja

ValueError: Unable to coerce to Series, length must be 12: given 0

In [159]:
a = pd.DataFrame({'a': [1,2,3], 'b': [4,5,6]})
a['c'] = a.apply(lambda x: print(type(x)) , axis=1)


# a.max().values.sum()
a

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


a  b     c
0  1  4  None
1  2  5  None
2  3  6  None

## Build reduced lineup dataset without any player seasons which aren't included in the cluster dataset

In [213]:
x = 5
player = a[a['b'] == x]
print(player)

# if player.empty:
if a[a['b'] == x].empty:
    print('Yea')
else: print('Nah')
#     print('yea')


   a  b     c
1  2  5  None
Nah


### Function for getting boolean for whether all players are in player cluster dataset

In [237]:
# for each lineup need to verify that all players are in the players df (re: id and year)

df = pd.read_csv('datasets/lineups/4man_lineups_300min_1997_2020.csv', index_col=0)
df = df[df['year'] >=2000]


def verify_players(lineup, df_players):
    """Return if all players in lineup are in the player cluster dataset, False otherwise"""
    
    player_ids = lineup['player_ids'].split(', ')
    year = lineup['year']
    
    for pid in player_ids:
        if df_players[(df_players['year']==year) & (df_players['player_id']==pid)].empty:
            return False
    return True


In [241]:
# lineup = df.iloc[25]
# print(lineup[['year', 'player_ids']])
indices = df.apply(lambda lineup: verify_players(lineup, df_players), axis=1)
indices

year                                                2003
player_ids    abdursh01, glovedi01, ratlith01, robingl01
Name: S. Abdur-Rahim | D. Glover | T. Ratliff | G. Robinson ATL 2003, dtype: object


lineup
B. Coles | A. Henderson | J. Jackson | D. Mutombo ATL 2000    True
A. Henderson | J. Jackson | D. Mutombo | I. Rider ATL 2000    True
B. Coles | A. Henderson | D. Mutombo | I. Rider ATL 2000      True
B. Coles | J. Jackson | D. Mutombo | I. Rider ATL 2000        True
B. Coles | A. Henderson | J. Jackson | I. Rider ATL 2000      True
                                                              ... 
T. Ariza | B. Beal | T. Bryant | T. Satoranský WAS 2019       True
B. Beal | T. Bryant | J. Green | T. Satoranský WAS 2019       True
T. Ariza | T. Bryant | J. Green | T. Satoranský WAS 2019      True
B. Beal | M. Morris | O. Porter | J. Wall WAS 2019            True
T. Ariza | B. Beal | J. Green | B. Portis WAS 2019            True
Length: 5253, dtype: bool

In [251]:
indices[indices==False]

lineup
J. Collier | S. Jackson | B. Sura | J. Terry ATL 2004                False
J. Kidd | K. Kittles | K. Martin | D. Mutombo NJN 2003               False
R. Jefferson | J. Kidd | K. Kittles | D. Mutombo NJN 2003            False
R. Jefferson | J. Kidd | K. Martin | D. Mutombo NJN 2003             False
Z. Ilgauskas | A. Miller | L. Murray | C. Weatherspoon CLE 2001      False
M. Harpring | Z. Ilgauskas | A. Miller | C. Weatherspoon CLE 2001    False
M. Harpring | Z. Ilgauskas | L. Murray | C. Weatherspoon CLE 2001    False
M. Harpring | Z. Ilgauskas | A. Miller | L. Murray CLE 2001          False
K. Irving | L. James | K. Love | A. Varejão CLE 2015                 False
D. Barros | M. Curry | C. Robinson | B. Wallace DET 2002             False
S. Battier | T. McGrady | D. Mutombo | L. Scola HOU 2008             False
R. Alston | T. McGrady | D. Mutombo | L. Scola HOU 2008              False
R. Alston | S. Battier | T. McGrady | D. Mutombo HOU 2008            False
T. Ariza | P. Beve

In [254]:
df.loc[indices[indices==False].index, 'player_ids']

lineup
J. Collier | S. Jackson | B. Sura | J. Terry ATL 2004                 collija02, jacksst02, surabo01, terryja01
J. Kidd | K. Kittles | K. Martin | D. Mutombo NJN 2003                kiddja01, kittlke01, martike01, mutomdi01
R. Jefferson | J. Kidd | K. Kittles | D. Mutombo NJN 2003             jefferi01, kiddja01, kittlke01, mutomdi01
R. Jefferson | J. Kidd | K. Martin | D. Mutombo NJN 2003              jefferi01, kiddja01, martike01, mutomdi01
Z. Ilgauskas | A. Miller | L. Murray | C. Weatherspoon CLE 2001      ilgauzy01, millean02, murrala01, weathcl01
M. Harpring | Z. Ilgauskas | A. Miller | C. Weatherspoon CLE 2001    harprma01, ilgauzy01, millean02, weathcl01
M. Harpring | Z. Ilgauskas | L. Murray | C. Weatherspoon CLE 2001    harprma01, ilgauzy01, murrala01, weathcl01
M. Harpring | Z. Ilgauskas | A. Miller | L. Murray CLE 2001          harprma01, ilgauzy01, millean02, murrala01
K. Irving | L. James | K. Love | A. Varejão CLE 2015                  irvinky01, jamesle01, lovek

In [256]:
year = 2004
# pid = 'collija02'
pid = 'jacksst02'
# , jacksst02, surabo01, terryja01


df_players[(df_players['year']==year) & (df_players['player_id']==pid)]

player_id pos  age team_id   g    mp   per  ts_pct  \
player                                                                     
Stephen Jackson 2004  jacksst02  SF   25     ATL  80  2940  16.1   0.521   

                      fg3a_per_fga_pct  fta_per_fga_pct  ...  cluster_2_bpm  \
player                                                   ...                  
Stephen Jackson 2004             0.339            0.236  ...            0.0   

                      cluster_3_bpm  cluster_4_bpm  cluster_5_bpm  \
player                                                              
Stephen Jackson 2004       0.005424            0.0            0.0   

                      cluster_6_bpm  cluster_7_bpm  cluster_8_bpm  \
player                                                              
Stephen Jackson 2004       0.021306            0.0       0.000005   

                      cluster_9_bpm  cluster_10_bpm  cluster_11_bpm  
player                                                               
Stephen Jackson 2004       0.000006             0.0             0.0  

[1 rows x 116 columns]

## Create and save CLEAN lineup versions from 2000-2020

In [ ]:
def verify_players(lineup, df_players):
    """Return if all players in lineup are in the player cluster dataset, False otherwise"""
    player_ids = lineup['player_ids'].split(', ')
    year = lineup['year']
    
    for pid in player_ids:
        if df_players[(df_players['year']==year) & (df_players['player_id']==pid)].empty:
            return False
    return True

In [261]:
## 4man lineups
df_all_4man = pd.read_csv('datasets/lineups/4man_lineups_300min_1997_2020.csv', index_col=0)
df_all_4man = df_all_4man[df_all_4man['year'] >=2000]
df_players = pd.read_csv('datasets/master_player_stats_bio_bpm_clusters.csv', index_col=0)

indices = df_all_4man.apply(lambda lineup: verify_players(lineup, df_players), axis=1)

clean_4man = df_all_4man.loc[indices[indices==True].index, :]
clean_4man.shape
clean_4man.to_csv('datasets/clean_4man_lineups_2000_2020.csv')

(5222, 27)

In [264]:
## 5man lineups
df_all_5man = pd.read_csv('datasets/lineups/5man_lineups_150min_1997_2020.csv', index_col=0)
df_all_5man = df_all_5man[df_all_5man['year'] >=2000]
df_players = pd.read_csv('datasets/master_player_stats_bio_bpm_clusters.csv', index_col=0)
indices = df_all_5man.apply(lambda lineup: verify_players(lineup, df_players), axis=1)
clean_5man = df_all_5man.loc[indices[indices==True].index, :]
df_all_5man.shape
clean_5man.shape
clean_5man.to_csv('datasets/clean_5man_lineups_2000_2020.csv')

(1730, 27)

(1682, 27)

## Now rerun the func for generating cluster profiles

In [50]:
def get_lineup_cluster_profile(lineup, df_players):
    """
    Function for building lineup cluster profiles (bpm weighted and non bpm weighted)
    based on player ids and year using a dataset with player cluster assignments and bpm weights.
    
    Return a 1 row dataframe with same index as lineup and columns for cluster profiles.
    """
    ## TRYING NOW TO RETURN A NP ARRAY
    
#     print('Called with lineup:', lineup)
    
    player_ids = lineup['player_ids'].split(', ')
    year = lineup['year']
    cluster_bpm_cols = [f'cluster_{n}_bpm' for n in range(12)]
    cluster_nonbpm_cols = [f'cluster_{n}' for n in range(12)]    
    
    lineup_bpm_clusters = np.zeros(12)
    lineup_nonbpm_clusters = np.zeros(12)
    
#     df_lineup_clusters = pd.DataFrame({col: 0.0 for col in cluster_bpm_cols+cluster_nonbpm_cols}, index=[lineup.name])
    
#     print('all lineup pids:', player_ids)
#     print('year:', year)

    for pid in player_ids:
        player = df_players[(df_players['year'] == year) & (df_players['player_id'] == pid)]
#         print('player: ', pid)
#         df_lineup_clusters[cluster_bpm_cols] += player[cluster_bpm_cols].to_numpy().reshape(-1)
#         df_lineup_clusters[cluster_nonbpm_cols] += player[cluster_nonbpm_cols].to_numpy().reshape(-1)
    
        lineup_bpm_clusters += player[cluster_bpm_cols].to_numpy().reshape(-1)
        lineup_nonbpm_clusters += player[cluster_nonbpm_cols].to_numpy().reshape(-1)
    
#     print('returning:', df_lineup_clusters)
#     print(df_lineup_clusters.shape)
#     print('---------------------')
    
#     return df_lineup_clusters

    return np.append(lineup_bpm_clusters, lineup_nonbpm_clusters)

In [119]:
%%time

df4man = pd.read_csv('datasets/lineups/clean_4man_lineups_2000_2020.csv', index_col=0)
df_players = pd.read_csv('datasets/master_player_stats_bio_bpm_clusters.csv', index_col=0)

cluster_bpm_cols = [f'cluster_{n}_bpm' for n in range(12)]
cluster_nonbpm_cols = [f'cluster_{n}' for n in range(12)]
cols = cluster_bpm_cols + cluster_nonbpm_cols

lineup_cluster_profile_series = df4man.apply(lambda lineup: get_lineup_cluster_profile(lineup, df_players), axis=1)
lineup_cluster_profiles = lineup_cluster_profile_series.values
lineup_cluster_profiles = [[val for val in lineup_cluster_profiles[row]] for row in range(len(lineup_cluster_profiles))]

df4man[cols] = lineup_cluster_profiles
df4man.to_csv('datasets/master_4man_lineup_clusters_2000_2020.csv')


#### FOR 5Man lineups
df5man = pd.read_csv('datasets/lineups/clean_5man_lineups_2000_2020.csv', index_col=0)
df_players = pd.read_csv('datasets/master_player_stats_bio_bpm_clusters.csv', index_col=0)

cluster_bpm_cols = [f'cluster_{n}_bpm' for n in range(12)]
cluster_nonbpm_cols = [f'cluster_{n}' for n in range(12)]
cols = cluster_bpm_cols + cluster_nonbpm_cols

lineup_cluster_profile_series = df5man.apply(lambda lineup: get_lineup_cluster_profile(lineup, df_players), axis=1)
lineup_cluster_profiles = lineup_cluster_profile_series.values
lineup_cluster_profiles = [[val for val in lineup_cluster_profiles[row]] for row in range(len(lineup_cluster_profiles))]

df5man[cols] = lineup_cluster_profiles
df5man.to_csv('datasets/master_5man_lineup_clusters_2000_2020.csv')




Wall time: 1min 9s


## Verify Lineup Clusters

In [38]:
df_players = pd.read_csv('datasets/master_player_stats_bio_bpm_clusters.csv', index_col=0)
df4 = pd.read_csv('datasets/master_4man_lineup_clusters_2000_2020.csv', index_col=0)
df5 = pd.read_csv('datasets/master_5man_lineup_clusters_2000_2020.csv', index_col=0)

cluster_bpm_cols = [f'cluster_{n}_bpm' for n in range(12)]
cluster_nonbpm_cols = [f'cluster_{n}' for n in range(12)]

for row in range(-1, -16, -1):
    lineup = df5.iloc[row]
    
    player_ids = lineup['player_ids'].split(', ')
    year = lineup['year']
    
    lineup_bpm_cluster = lineup[cluster_bpm_cols]
    lineup_nonbpm_cluster = lineup[cluster_nonbpm_cols]
    player_bpm_cluster_sum = np.zeros(12)
    for pid in player_ids:
        player = df_players[(df_players['year']==year) & (df_players['player_id']==pid)]
        player_bpm_cluster_sum += player[cluster_bpm_cols].values.reshape(-1)
        
    print(player_bpm_cluster_sum.round(2))
    print(lineup[cluster_bpm_cols].values.astype(float).reshape(-1).round(2))
    print('\n')
    
## Checks out

[ 0.   -0.98  0.    2.9   0.   -4.3  -0.15  0.   -0.91  0.   -0.   -0.26]
[ 0.   -0.98  0.    2.9   0.   -4.3  -0.15  0.   -0.91  0.   -0.   -0.26]


[ 0.   -2.57  0.    2.75  0.    0.   -0.7   0.   -2.4   0.02 -0.   -0.  ]
[ 0.   -2.57  0.    2.75  0.    0.   -0.7   0.   -2.4   0.02 -0.   -0.  ]


[ 0.   -2.57  0.    2.75  0.    0.   -0.7   0.    1.99  0.02 -0.   -0.  ]
[ 0.   -2.57  0.    2.75  0.    0.   -0.7   0.    1.99  0.02 -0.   -0.  ]


[ 0.   -1.71  0.    0.    0.   -0.    0.05 -4.4  -0.06  0.    1.14 -2.73]
[ 0.   -1.71  0.    0.    0.   -0.    0.05 -4.4  -0.06  0.    1.14 -2.73]


[ 0.   -1.71  0.    0.    0.   -0.   -0.   -4.4  -0.06  0.   -0.9  -2.73]
[ 0.   -1.71  0.    0.    0.   -0.   -0.   -4.4  -0.06  0.   -0.9  -2.73]


[ 0.    2.48  0.    2.71  0.    0.   -1.1  -0.6   0.01  0.3  -0.9   0.  ]
[ 0.    2.48  0.    2.71  0.    0.   -1.1  -0.6   0.01  0.3  -0.9   0.  ]


[ 0.    0.78  0.    4.61  0.    0.    1.3  -0.6   0.02  0.3   0.   -0.  ]
[ 0.    0.78  0.    4.61  

In [50]:
year = 2018
pid = 'anthoca01'
pid = 'georgpa01'
df_players[(df_players['player_id']==pid) & (df_players['year']==year)][cluster_bpm_cols]

cluster_0_bpm  cluster_1_bpm  cluster_2_bpm  cluster_3_bpm  \
player                                                                         
Paul George 2018            0.0            0.0            0.0       2.817959   

                  cluster_4_bpm  cluster_5_bpm  cluster_6_bpm  cluster_7_bpm  \
player                                                                         
Paul George 2018            0.0            0.0       0.000226            0.0   

                  cluster_8_bpm  cluster_9_bpm  cluster_10_bpm  cluster_11_bpm  
player                                                                          
Paul George 2018            0.0       0.081815             0.0             0.0

In [51]:
df4.sort_values(by='cluster_2_bpm')[['diff_pts']+cluster_bpm_cols]

diff_pts  cluster_0_bpm  \
lineup                                                                        
K. Bryant | J. Clarkson | J. Randle | D. Russel...     -19.4       0.000000   
J. Clarkson | R. Hibbert | J. Randle | L. Willi...     -20.1      -0.000006   
K. Bryant | J. Clarkson | J. Randle | L. Willia...     -22.7       0.000000   
K. Bryant | R. Hibbert | J. Randle | D. Russell...     -24.9      -0.000006   
J. Clarkson | R. Hibbert | J. Randle | D. Russe...     -20.0      -0.000006   
...                                                      ...            ...   
C. Brown | T. Duncan | A. Johnson | D. Robinson...       6.9      -0.005877   
C. Brown | T. Duncan | M. Elie | D. Robinson SA...       8.5      -0.005877   
T. Duncan | A. Johnson | J. Kersey | D. Robinso...       9.0      -0.298039   
T. Duncan | M. Elie | T. Porter | D. Robinson S...      14.0       0.000000   
T. Duncan | M. Elie | J. Jackson | D. Robinson ...       5.3       0.000000   

                                                    cluster_1_bpm  \
lineup                                                              
K. Bryant | J. Clarkson | J. Randle | D. Russel...      -0.000033   
J. Clarkson | R. Hibbert | J. Randle | L. Willi...      -0.000030   
K. Bryant | J. Clarkson | J. Randle | L. Willia...      -0.000030   
K. Bryant | R. Hibbert | J. Randle | D. Russell...      -0.000002   
J. Clarkson | R. Hibbert | J. Randle | D. Russe...      -0.000033   
...                                                           ...   
C. Brown | T. Duncan | A. Johnson | D. Robinson...       0.000000   
C. Brown | T. Duncan | M. Elie | D. Robinson SA...      -0.299950   
T. Duncan | A. Johnson | J. Kersey | D. Robinso...       0.000000   
T. Duncan | M. Elie | T. Porter | D. Robinson S...      -0.299950   
T. Duncan | M. Elie | J. Jackson | D. Robinson ...      -0.713337   

                                                    cluster_2_bpm  \
lineup                                                              
K. Bryant | J. Clarkson | J. Randle | D. Russel...      -3.198307   
J. Clarkson | R. Hibbert | J. Randle | L. Willi...      -3.198307   
K. Bryant | J. Clarkson | J. Randle | L. Willia...      -3.198307   
K. Bryant | R. Hibbert | J. Randle | D. Russell...      -3.198307   
J. Clarkson | R. Hibbert | J. Randle | D. Russe...      -3.198307   
...                                                           ...   
C. Brown | T. Duncan | A. Johnson | D. Robinson...      11.499429   
C. Brown | T. Duncan | M. Elie | D. Robinson SA...      11.499429   
T. Duncan | A. Johnson | J. Kersey | D. Robinso...      11.499429   
T. Duncan | M. Elie | T. Porter | D. Robinson S...      11.499429   
T. Duncan | M. Elie | J. Jackson | D. Robinson ...      11.499429   

                                                    cluster_3_bpm  \
lineup                                                              
K. Bryant | J. Clarkson | J. Randle | D. Russel...      -1.594120   
J. Clarkson | R. Hibbert | J. Randle | L. Willi...      -1.593909   
K. Bryant | J. Clarkson | J. Randle | L. Willia...      -1.594120   
K. Bryant | R. Hibbert | J. Randle | D. Russell...      -0.000211   
J. Clarkson | R. Hibbert | J. Randle | D. Russe...      -1.593909   
...                                                           ...   
C. Brown | T. Duncan | A. Johnson | D. Robinson...       0.000000   
C. Brown | T. Duncan | M. Elie | D. Robinson SA...      -0.000032   
T. Duncan | A. Johnson | J. Kersey | D. Robinso...       0.000000   
T. Duncan | M. Elie | T. Porter | D. Robinson S...      -0.000032   
T. Duncan | M. Elie | J. Jackson | D. Robinson ...      -0.000032   

                                                    cluster_4_bpm  \
lineup                                                              
K. Bryant | J. Clarkson | J. Randle | D. Russel...            0.0   
J. Clarkson | R. Hibbert | J. Randle | L. Willi...            0.0   
K. Bryant | J. Clarkson | J. Randle | L. Willia...    

## Worksheet

In [123]:
## check that bpm cols and nonbpm didn't get confused
df4man[cluster_nonbpm_cols].sum(axis=1)
## checks out

lineup
B. Coles | A. Henderson | J. Jackson | D. Mutombo ATL 2000    3.999999
A. Henderson | J. Jackson | D. Mutombo | I. Rider ATL 2000    4.000000
B. Coles | A. Henderson | D. Mutombo | I. Rider ATL 2000      3.999999
B. Coles | J. Jackson | D. Mutombo | I. Rider ATL 2000        3.999999
B. Coles | A. Henderson | J. Jackson | I. Rider ATL 2000      3.999999
                                                                ...   
T. Ariza | B. Beal | T. Bryant | T. Satoranský WAS 2019       3.999999
B. Beal | T. Bryant | J. Green | T. Satoranský WAS 2019       4.000000
T. Ariza | T. Bryant | J. Green | T. Satoranský WAS 2019      3.999999
B. Beal | M. Morris | O. Porter | J. Wall WAS 2019            3.999999
T. Ariza | B. Beal | J. Green | B. Portis WAS 2019            3.999999
Length: 5222, dtype: float64

In [118]:
df = pd.read_csv('datasets/clean_4man_lineups_2000_2020.csv', index_col=0)
last_row = df.iloc[-1]
# last_row
x = get_lineup_cluster_profile(last_row, df_players)
x[0:12].round(2)

array([ 0.  , -2.57,  0.  ,  2.75,  0.  ,  0.  , -0.  ,  0.  , -2.4 ,
        0.02,  0.  , -0.  ])

In [112]:
df4man = pd.read_csv('datasets/clean_4man_lineups_2000_2020.csv', index_col=0)
cols = cluster_bpm_cols + cluster_nonbpm_cols
# df4man[cols] = x.values


# lineup_clusters = lineup_cluster_profile_series.values

lineup_cluster_profiles = lineup_cluster_profile_series.values
lineup_cluster_profiles = [[val for val in lineup_cluster_profiles[row]] for row in range(len(lineup_cluster_profiles))]
df4man[cols] = lineup_cluster_profiles
df4man[cluster_bpm_cols].head()


# = val for val in lineup_cluster_profile_series.values



# y = [[val for val in x.values[row]] for row in range(len(x))]
# # y[3][0:12]
# # df_x = 
# df_x = pd.DataFrame(y, columns=cols, index=x.index)
# df_x.iloc[3]
# x

# len(df4man)
# len(x[0])
# len(cols)



cluster_0_bpm  \
lineup                                                              
B. Coles | A. Henderson | J. Jackson | D. Mutom...      -0.136912   
A. Henderson | J. Jackson | D. Mutombo | I. Rid...      -0.136912   
B. Coles | A. Henderson | D. Mutombo | I. Rider...      -0.136912   
B. Coles | J. Jackson | D. Mutombo | I. Rider A...       0.000000   
B. Coles | A. Henderson | J. Jackson | I. Rider...      -0.136912   

                                                    cluster_1_bpm  \
lineup                                                              
B. Coles | A. Henderson | J. Jackson | D. Mutom...      -0.000206   
A. Henderson | J. Jackson | D. Mutombo | I. Rid...      -0.000206   
B. Coles | A. Henderson | D. Mutombo | I. Rider...       0.000000   
B. Coles | J. Jackson | D. Mutombo | I. Rider A...      -0.000206   
B. Coles | A. Henderson | J. Jackson | I. Rider...      -0.000206   

                                                    cluster_2_bpm  \
lineup                                                              
B. Coles | A. Henderson | J. Jackson | D. Mutom...      -1.463069   
A. Henderson | J. Jackson | D. Mutombo | I. Rid...      -1.463069   
B. Coles | A. Henderson | D. Mutombo | I. Rider...      -1.463069   
B. Coles | J. Jackson | D. Mutombo | I. Rider A...       0.000000   
B. Coles | A. Henderson | J. Jackson | I. Rider...      -1.463069   

                                                    cluster_3_bpm  \
lineup                                                              
B. Coles | A. Henderson | J. Jackson | D. Mutom...      -0.000226   
A. Henderson | J. Jackson | D. Mutombo | I. Rid...      -0.000226   
B. Coles | A. Henderson | D. Mutombo | I. Rider...       0.000000   
B. Coles | J. Jackson | D. Mutombo | I. Rider A...      -0.000226   
B. Coles | A. Henderson | J. Jackson | I. Rider...      -0.000226   

                                                    cluster_4_bpm  \
lineup                                                              
B. Coles | A. Henderson | J. Jackson | D. Mutom...            0.0   
A. Henderson | J. Jackson | D. Mutombo | I. Rid...            0.0   
B. Coles | A. Henderson | D. Mutombo | I. Rider...            0.0   
B. Coles | J. Jackson | D. Mutombo | I. Rider A...            0.0   
B. Coles | A. Henderson | J. Jackson | I. Rider...            0.0   

                                                    cluster_5_bpm  \
lineup                                                              
B. Coles | A. Henderson | J. Jackson | D. Mutom...  -7.884000e-04   
A. Henderson | J. Jackson | D. Mutombo | I. Rid...  -8.000000e-07   
B. Coles | A. Henderson | D. Mutombo | I. Rider...  -7.876000e-04   
B. Coles | J. Jackson | D. Mutombo | I. Rider A...  -7.884000e-04   
B. Coles | A. Henderson | J. Jackson | I. Rider...  -7.884000e-04   

                                                    cluster_6_bpm  \
lineup                                                              
B. Coles | A. Henderson | J. Jackson | D. Mutom...      -0.799564   
A. Henderson | J. Jackson | D. Mutombo | I. Rid...      -2.199564   
B. Coles | A. Henderson | D. Mutombo | I. Rider...      -1.400000   
B. Coles | J. Jackson | D. Mutombo | I. Rider A...      -2.199564   
B. Coles | A. Henderson | J. Jackson | I. Rider...      -2.199564   

                                                    cluster_7_bpm  \
lineup                                                              
B. Coles | A. Henderson | J. Jackson | D. Mutom...            2.4   
A. Henderson | J. Jackson | D. Mutombo | I. Rid...            2.4   
B. Coles | A. Henderson | D. Mutombo | I. Rider...            2.4   
B. Coles | J. Jackson | D. Mutombo | I. Rider A...            2.4   
B. Coles | A. Henderson | J. Jackson | I. Rider...            0.0   

                                                    cluster_8_bpm  \
lineup                                                              
B. Coles | A. Henderson | J. Jackson | D. 

In [57]:
type(x)
# y = list(x.items())
x[3][0:12].round(2)
# type(x[0])
# x[0]
# y = x[0].to_series()
# y
# df = df4man.copy()
# df[cluster_bpm_cols+cluster_nonbpm_cols] = x
# df.head()

pandas.core.series.Series

array([ 0. , -0. ,  0. , -0. ,  0. , -0. , -2.2,  2.4, -0. ,  0. , -2.2,
        0. ])

In [59]:
t = get_lineup_cluster_profile(df4man.iloc[3], df_players)
t[0:12].round(2)

array([ 0. , -0. ,  0. , -0. ,  0. , -0. , -2.2,  2.4, -0. ,  0. , -2.2,
        0. ])